server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://192.168.145.10:3306/Spider?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: wsqboy518

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl