import Head from 'next/head'
import Image from 'next/image'

import styles from '@/styles/Home.module.css'
import { useState } from 'react';




export default function Home() {

  const cards = [{
    value : 'A',
    suit : 'spade'
  },{
    value : '2',
    suit : 'heart'
  },{
    value : '3',
    suit : 'club'
  },{
    value : 'J',
    suit : 'club'
  },{
    value : 'K',
    suit : 'heart'
  },{
    value : 'J',
    suit : 'diamond'
  }]


  const names = ['Ada Lovelace', 'Grace Hopper', 'Margaret Hamilton'];

  const [likes, setLikes] = useState(0);

  function handleClick() {
    setLikes(likes + 1);
  }


  function Card(props){

    return  <div className={styles.card} >
              <div className={styles.front}>
                  <div className={styles.value}>
                    <Image alt='' src={ (props.suit==='spade' || props.suit==='club') ? `./svg/${props.value}.svg` : `./svg/${props.value}_red.svg`} width={200} height={200}></Image>
                  </div>
                  <div className={styles.suit}>
                    <Image alt='' src={`./svg/${props.suit}.svg`} width={200} height={200}></Image>
                  </div>
                  <div className={styles.content}>
                    <Image alt='' src={`./svg/${props.suit}_${props.value}_content.svg`} width={200} height={200}></Image>
                  </div>
              </div>
              <div className={styles.back}>
                  <img src="./svg/back.svg" />
              </div>
          </div>
  }


  return (
    <>
      <Head>
        <title>Spider Pocket</title>
        <meta name="description" content="Generated by create wov." />
        <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
        <meta name="theme-color" content="#85BC87" />       
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.gameContainer}>
          <div className={styles.cardsContainer}>
          {cards.map((card,card_index) => (
            <Card key={`card_${card_index}`} value={card.value} suit={card.suit}></Card>
          ))}

          </div>
          <div className={styles.controlContainer}>
            <button>MENU</button>
          </div>
        </div>

        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  )
}
